// ═══════════════════════════════════════════════════════════════
// THEME TOKENS — All preset definitions for layout, scale, colors
// This is the "database" of all visual options.
// Admin picks one from each dimension → CSS vars are injected on <html>
// ═══════════════════════════════════════════════════════════════

// ── LAYOUT PRESETS ──────────────────────────────────────────────
// Controls: card shape, grid vs list, sidebar, nav style, shadows

export const LAYOUT_PRESETS = {
  modern: {
    '--layout-name': 'modern',
    '--card-border-radius': '1rem',
    '--card-shadow': '0 1px 3px rgba(0,0,0,0.08)',
    '--card-shadow-hover': '0 8px 25px rgba(0,0,0,0.12)',
    '--card-border': 'none',
    '--card-bg': 'var(--color-surface)',
    '--card-direction': 'row',
    '--card-image-width': '200px',
    '--card-image-height': '150px',
    '--card-image-ratio': '4/3',
    '--grid-columns': '1',
    '--nav-style': 'sticky',
    '--nav-blur': 'blur(16px) saturate(180%)',
    '--nav-bg': 'rgba(255,255,255,0.7)',
    '--nav-bg-dark': 'rgba(15,15,15,0.7)',
    '--sidebar-width': '320px',
    '--sidebar-display': 'block',
    '--border-radius-sm': '0.5rem',
    '--border-radius-md': '0.75rem',
    '--border-radius-lg': '1rem',
    '--border-radius-xl': '1.5rem',
    '--content-max-width': '1200px',
    '--deal-temp-style': 'pill',
    // Glass effect tokens
    '--glass-bg': 'rgba(255,255,255,0.6)',
    '--glass-bg-dark': 'rgba(30,30,30,0.6)',
    '--glass-blur': 'blur(16px) saturate(180%)',
    '--glass-border': '1px solid rgba(255,255,255,0.2)',
    '--glass-border-dark': '1px solid rgba(255,255,255,0.08)',
  },
  minimalist: {
    '--layout-name': 'minimalist',
    '--card-border-radius': '0',
    '--card-shadow': 'none',
    '--card-shadow-hover': 'none',
    '--card-border': '1px solid var(--color-border)',
    '--card-bg': 'transparent',
    '--card-direction': 'row',
    '--card-image-width': '120px',
    '--card-image-height': '90px',
    '--card-image-ratio': '4/3',
    '--grid-columns': '1',
    '--nav-style': 'static',
    '--nav-blur': 'none',
    '--nav-bg': 'var(--color-surface)',
    '--nav-bg-dark': 'var(--color-surface)',
    '--sidebar-width': '280px',
    '--sidebar-display': 'block',
    '--border-radius-sm': '2px',
    '--border-radius-md': '4px',
    '--border-radius-lg': '6px',
    '--border-radius-xl': '8px',
    '--content-max-width': '900px',
    '--deal-temp-style': 'text',
    '--glass-bg': 'var(--color-surface)',
    '--glass-bg-dark': 'var(--color-surface)',
    '--glass-blur': 'none',
    '--glass-border': '1px solid var(--color-border)',
    '--glass-border-dark': '1px solid var(--color-border)',
  },
  mydealz: {
    '--layout-name': 'mydealz',
    '--card-border-radius': '0.5rem',
    '--card-shadow': '0 1px 2px rgba(0,0,0,0.06)',
    '--card-shadow-hover': '0 4px 12px rgba(0,0,0,0.1)',
    '--card-border': '1px solid var(--color-border)',
    '--card-bg': 'var(--color-surface)',
    '--card-direction': 'row',
    '--card-image-width': '180px',
    '--card-image-height': '135px',
    '--card-image-ratio': '4/3',
    '--grid-columns': '1',
    '--nav-style': 'sticky',
    '--nav-blur': 'none',
    '--nav-bg': 'var(--color-primary)',
    '--nav-bg-dark': 'var(--color-primary)',
    '--sidebar-width': '300px',
    '--sidebar-display': 'block',
    '--border-radius-sm': '0.25rem',
    '--border-radius-md': '0.5rem',
    '--border-radius-lg': '0.75rem',
    '--border-radius-xl': '1rem',
    '--content-max-width': '1100px',
    '--deal-temp-style': 'badge',
    '--glass-bg': 'rgba(255,255,255,0.85)',
    '--glass-bg-dark': 'rgba(30,30,30,0.85)',
    '--glass-blur': 'blur(8px)',
    '--glass-border': '1px solid rgba(255,255,255,0.15)',
    '--glass-border-dark': '1px solid rgba(255,255,255,0.06)',
  },
  aliexpress: {
    '--layout-name': 'aliexpress',
    '--card-border-radius': '0.75rem',
    '--card-shadow': '0 2px 8px rgba(0,0,0,0.06)',
    '--card-shadow-hover': '0 4px 16px rgba(0,0,0,0.12)',
    '--card-border': 'none',
    '--card-bg': 'var(--color-surface)',
    '--card-direction': 'column',
    '--card-image-width': '100%',
    '--card-image-height': '200px',
    '--card-image-ratio': '1/1',
    '--grid-columns': '4',
    '--nav-style': 'sticky',
    '--nav-blur': 'blur(12px)',
    '--nav-bg': 'rgba(255,255,255,0.8)',
    '--nav-bg-dark': 'rgba(15,15,15,0.8)',
    '--sidebar-width': '0px',
    '--sidebar-display': 'none',
    '--border-radius-sm': '0.5rem',
    '--border-radius-md': '0.75rem',
    '--border-radius-lg': '1rem',
    '--border-radius-xl': '1.25rem',
    '--content-max-width': '1400px',
    '--deal-temp-style': 'badge',
    '--glass-bg': 'rgba(255,255,255,0.65)',
    '--glass-bg-dark': 'rgba(30,30,30,0.65)',
    '--glass-blur': 'blur(12px) saturate(150%)',
    '--glass-border': '1px solid rgba(255,255,255,0.18)',
    '--glass-border-dark': '1px solid rgba(255,255,255,0.07)',
  },
  shopee: {
    '--layout-name': 'shopee',
    '--card-border-radius': '0.25rem',
    '--card-shadow': '0 1px 1px rgba(0,0,0,0.05)',
    '--card-shadow-hover': '0 2px 8px rgba(0,0,0,0.1)',
    '--card-border': '1px solid var(--color-border)',
    '--card-bg': 'var(--color-surface)',
    '--card-direction': 'column',
    '--card-image-width': '100%',
    '--card-image-height': '180px',
    '--card-image-ratio': '1/1',
    '--grid-columns': '5',
    '--nav-style': 'sticky',
    '--nav-blur': 'none',
    '--nav-bg': 'var(--color-primary)',
    '--nav-bg-dark': 'var(--color-primary)',
    '--sidebar-width': '220px',
    '--sidebar-display': 'block',
    '--border-radius-sm': '0.125rem',
    '--border-radius-md': '0.25rem',
    '--border-radius-lg': '0.375rem',
    '--border-radius-xl': '0.5rem',
    '--content-max-width': '1400px',
    '--deal-temp-style': 'pill',
    '--glass-bg': 'rgba(255,255,255,0.9)',
    '--glass-bg-dark': 'rgba(30,30,30,0.9)',
    '--glass-blur': 'blur(6px)',
    '--glass-border': '1px solid rgba(255,255,255,0.1)',
    '--glass-border-dark': '1px solid rgba(255,255,255,0.05)',
  },
} as const

// ── SCALE PRESETS (5 levels) ────────────────────────────────────

export const SCALE_PRESETS = {
  xs: {
    '--font-size-xs': '0.625rem', '--font-size-sm': '0.6875rem', '--font-size-base': '0.75rem',
    '--font-size-lg': '0.875rem', '--font-size-xl': '1rem', '--font-size-2xl': '1.25rem',
    '--card-padding': '0.5rem', '--card-gap': '0.5rem', '--section-gap': '0.75rem',
    '--nav-height': '40px', '--avatar-size': '24px', '--button-height': '28px', '--icon-size': '14px',
  },
  sm: {
    '--font-size-xs': '0.6875rem', '--font-size-sm': '0.75rem', '--font-size-base': '0.8125rem',
    '--font-size-lg': '0.9375rem', '--font-size-xl': '1.125rem', '--font-size-2xl': '1.5rem',
    '--card-padding': '0.625rem', '--card-gap': '0.625rem', '--section-gap': '1rem',
    '--nav-height': '48px', '--avatar-size': '28px', '--button-height': '32px', '--icon-size': '16px',
  },
  md: {
    '--font-size-xs': '0.75rem', '--font-size-sm': '0.8125rem', '--font-size-base': '0.875rem',
    '--font-size-lg': '1rem', '--font-size-xl': '1.25rem', '--font-size-2xl': '1.75rem',
    '--card-padding': '0.75rem', '--card-gap': '0.75rem', '--section-gap': '1.25rem',
    '--nav-height': '56px', '--avatar-size': '32px', '--button-height': '36px', '--icon-size': '18px',
  },
  lg: {
    '--font-size-xs': '0.8125rem', '--font-size-sm': '0.875rem', '--font-size-base': '1rem',
    '--font-size-lg': '1.125rem', '--font-size-xl': '1.5rem', '--font-size-2xl': '2rem',
    '--card-padding': '1rem', '--card-gap': '1rem', '--section-gap': '1.5rem',
    '--nav-height': '64px', '--avatar-size': '40px', '--button-height': '42px', '--icon-size': '20px',
  },
  xl: {
    '--font-size-xs': '0.875rem', '--font-size-sm': '1rem', '--font-size-base': '1.125rem',
    '--font-size-lg': '1.25rem', '--font-size-xl': '1.75rem', '--font-size-2xl': '2.5rem',
    '--card-padding': '1.25rem', '--card-gap': '1.25rem', '--section-gap': '2rem',
    '--nav-height': '72px', '--avatar-size': '48px', '--button-height': '48px', '--icon-size': '24px',
  },
} as const

// ── COLOR SCHEMES (light + dark for each) ──────────────────────

export const COLOR_SCHEMES = {
  default: {
    light: {
      '--color-bg': '#F8F7F4', '--color-surface': '#FFFFFF', '--color-primary': '#FF4500',
      '--color-primary-hover': '#E03E00', '--color-primary-text': '#FFFFFF', '--color-secondary': '#FF6B35',
      '--color-accent': '#FFD700', '--color-text': '#1A1A1A', '--color-text-muted': '#6B7280',
      '--color-border': '#E5E7EB', '--color-hot': '#FF4500', '--color-cold': '#4FC3F7',
      '--color-success': '#10B981', '--color-danger': '#EF4444', '--color-sponsored': '#9C27B0',
    },
    dark: {
      '--color-bg': '#0F0F0F', '--color-surface': '#1A1A1A', '--color-primary': '#FF5722',
      '--color-primary-hover': '#FF7043', '--color-primary-text': '#FFFFFF', '--color-secondary': '#FF8A65',
      '--color-accent': '#FFD700', '--color-text': '#F5F5F5', '--color-text-muted': '#9CA3AF',
      '--color-border': '#2D2D2D', '--color-hot': '#FF5722', '--color-cold': '#4FC3F7',
      '--color-success': '#34D399', '--color-danger': '#F87171', '--color-sponsored': '#CE93D8',
    },
  },
  'dark-orange': {
    light: {
      '--color-bg': '#FFF8F0', '--color-surface': '#FFFFFF', '--color-primary': '#E65100',
      '--color-primary-hover': '#BF360C', '--color-primary-text': '#FFFFFF', '--color-secondary': '#F4511E',
      '--color-accent': '#FFB300', '--color-text': '#212121', '--color-text-muted': '#757575',
      '--color-border': '#FFE0B2', '--color-hot': '#E65100', '--color-cold': '#0288D1',
      '--color-success': '#2E7D32', '--color-danger': '#C62828', '--color-sponsored': '#6A1B9A',
    },
    dark: {
      '--color-bg': '#1A0E00', '--color-surface': '#2A1800', '--color-primary': '#FF6D00',
      '--color-primary-hover': '#FF9100', '--color-primary-text': '#000000', '--color-secondary': '#FF8F00',
      '--color-accent': '#FFD600', '--color-text': '#FFF3E0', '--color-text-muted': '#FFAB91',
      '--color-border': '#3E2723', '--color-hot': '#FF6D00', '--color-cold': '#29B6F6',
      '--color-success': '#66BB6A', '--color-danger': '#EF5350', '--color-sponsored': '#CE93D8',
    },
  },
  ocean: {
    light: {
      '--color-bg': '#F0F7FF', '--color-surface': '#FFFFFF', '--color-primary': '#0077B6',
      '--color-primary-hover': '#005F8C', '--color-primary-text': '#FFFFFF', '--color-secondary': '#00B4D8',
      '--color-accent': '#90E0EF', '--color-text': '#03045E', '--color-text-muted': '#6B7280',
      '--color-border': '#CAF0F8', '--color-hot': '#E63946', '--color-cold': '#0077B6',
      '--color-success': '#06D6A0', '--color-danger': '#E63946', '--color-sponsored': '#7209B7',
    },
    dark: {
      '--color-bg': '#03045E', '--color-surface': '#0A1128', '--color-primary': '#00B4D8',
      '--color-primary-hover': '#48CAE4', '--color-primary-text': '#03045E', '--color-secondary': '#90E0EF',
      '--color-accent': '#CAF0F8', '--color-text': '#F0F7FF', '--color-text-muted': '#90E0EF',
      '--color-border': '#1B2845', '--color-hot': '#FF6B6B', '--color-cold': '#00B4D8',
      '--color-success': '#06D6A0', '--color-danger': '#FF6B6B', '--color-sponsored': '#C77DFF',
    },
  },
  forest: {
    light: {
      '--color-bg': '#F5F7F0', '--color-surface': '#FFFFFF', '--color-primary': '#2D6A4F',
      '--color-primary-hover': '#1B4332', '--color-primary-text': '#FFFFFF', '--color-secondary': '#52B788',
      '--color-accent': '#D4A373', '--color-text': '#1B4332', '--color-text-muted': '#6B7280',
      '--color-border': '#D8E2DC', '--color-hot': '#E76F51', '--color-cold': '#2D6A4F',
      '--color-success': '#40916C', '--color-danger': '#E76F51', '--color-sponsored': '#7B2CBF',
    },
    dark: {
      '--color-bg': '#0B1F0E', '--color-surface': '#132A13', '--color-primary': '#52B788',
      '--color-primary-hover': '#74C69D', '--color-primary-text': '#0B1F0E', '--color-secondary': '#95D5B2',
      '--color-accent': '#DDA15E', '--color-text': '#EFF6EF', '--color-text-muted': '#95D5B2',
      '--color-border': '#1E3F20', '--color-hot': '#FF8A65', '--color-cold': '#52B788',
      '--color-success': '#74C69D', '--color-danger': '#FF8A65', '--color-sponsored': '#D4A5FF',
    },
  },
  sunset: {
    light: {
      '--color-bg': '#FFF5F5', '--color-surface': '#FFFFFF', '--color-primary': '#C2185B',
      '--color-primary-hover': '#AD1457', '--color-primary-text': '#FFFFFF', '--color-secondary': '#FF6F00',
      '--color-accent': '#FFD54F', '--color-text': '#212121', '--color-text-muted': '#757575',
      '--color-border': '#FFCDD2', '--color-hot': '#FF5722', '--color-cold': '#0097A7',
      '--color-success': '#00897B', '--color-danger': '#D32F2F', '--color-sponsored': '#6A1B9A',
    },
    dark: {
      '--color-bg': '#1A0A10', '--color-surface': '#2A1520', '--color-primary': '#F48FB1',
      '--color-primary-hover': '#F06292', '--color-primary-text': '#1A0A10', '--color-secondary': '#FFB74D',
      '--color-accent': '#FFE082', '--color-text': '#FFF5F5', '--color-text-muted': '#F48FB1',
      '--color-border': '#3E1A2A', '--color-hot': '#FF8A65', '--color-cold': '#4DD0E1',
      '--color-success': '#4DB6AC', '--color-danger': '#EF5350', '--color-sponsored': '#CE93D8',
    },
  },
  midnight: {
    light: {
      '--color-bg': '#F5F5F7', '--color-surface': '#FFFFFF', '--color-primary': '#1E1E2E',
      '--color-primary-hover': '#313244', '--color-primary-text': '#FFFFFF', '--color-secondary': '#6C7086',
      '--color-accent': '#F5C2E7', '--color-text': '#1E1E2E', '--color-text-muted': '#6C7086',
      '--color-border': '#E0E0E5', '--color-hot': '#F38BA8', '--color-cold': '#89B4FA',
      '--color-success': '#A6E3A1', '--color-danger': '#F38BA8', '--color-sponsored': '#CBA6F7',
    },
    dark: {
      '--color-bg': '#1E1E2E', '--color-surface': '#181825', '--color-primary': '#CDD6F4',
      '--color-primary-hover': '#BAC2DE', '--color-primary-text': '#1E1E2E', '--color-secondary': '#A6ADC8',
      '--color-accent': '#F5C2E7', '--color-text': '#CDD6F4', '--color-text-muted': '#6C7086',
      '--color-border': '#313244', '--color-hot': '#F38BA8', '--color-cold': '#89B4FA',
      '--color-success': '#A6E3A1', '--color-danger': '#F38BA8', '--color-sponsored': '#CBA6F7',
    },
  },
  rose: {
    light: {
      '--color-bg': '#FFF1F2', '--color-surface': '#FFFFFF', '--color-primary': '#E11D48',
      '--color-primary-hover': '#BE123C', '--color-primary-text': '#FFFFFF', '--color-secondary': '#FB7185',
      '--color-accent': '#FFC0CB', '--color-text': '#1F1F1F', '--color-text-muted': '#6B7280',
      '--color-border': '#FFE4E6', '--color-hot': '#E11D48', '--color-cold': '#3B82F6',
      '--color-success': '#10B981', '--color-danger': '#E11D48', '--color-sponsored': '#8B5CF6',
    },
    dark: {
      '--color-bg': '#1A0A0E', '--color-surface': '#2A1015', '--color-primary': '#FB7185',
      '--color-primary-hover': '#FDA4AF', '--color-primary-text': '#1A0A0E', '--color-secondary': '#FDA4AF',
      '--color-accent': '#FFC0CB', '--color-text': '#FFF1F2', '--color-text-muted': '#FB7185',
      '--color-border': '#3E1520', '--color-hot': '#FB7185', '--color-cold': '#60A5FA',
      '--color-success': '#34D399', '--color-danger': '#FB7185', '--color-sponsored': '#A78BFA',
    },
  },
  monochrome: {
    light: {
      '--color-bg': '#FAFAFA', '--color-surface': '#FFFFFF', '--color-primary': '#171717',
      '--color-primary-hover': '#404040', '--color-primary-text': '#FFFFFF', '--color-secondary': '#525252',
      '--color-accent': '#A3A3A3', '--color-text': '#0A0A0A', '--color-text-muted': '#737373',
      '--color-border': '#E5E5E5', '--color-hot': '#DC2626', '--color-cold': '#2563EB',
      '--color-success': '#16A34A', '--color-danger': '#DC2626', '--color-sponsored': '#7C3AED',
    },
    dark: {
      '--color-bg': '#0A0A0A', '--color-surface': '#171717', '--color-primary': '#FAFAFA',
      '--color-primary-hover': '#E5E5E5', '--color-primary-text': '#0A0A0A', '--color-secondary': '#A3A3A3',
      '--color-accent': '#525252', '--color-text': '#FAFAFA', '--color-text-muted': '#A3A3A3',
      '--color-border': '#262626', '--color-hot': '#EF4444', '--color-cold': '#3B82F6',
      '--color-success': '#22C55E', '--color-danger': '#EF4444', '--color-sponsored': '#8B5CF6',
    },
  },
  // ── VIETNAMESE FESTIVAL THEMES ──
  tet: {
    light: {
      '--color-bg': '#FFF8E7', '--color-surface': '#FFFFFF', '--color-primary': '#C62828',
      '--color-primary-hover': '#B71C1C', '--color-primary-text': '#FFFFFF', '--color-secondary': '#F9A825',
      '--color-accent': '#FFD600', '--color-text': '#3E2723', '--color-text-muted': '#795548',
      '--color-border': '#FFE0B2', '--color-hot': '#D32F2F', '--color-cold': '#1565C0',
      '--color-success': '#2E7D32', '--color-danger': '#C62828', '--color-sponsored': '#AD1457',
    },
    dark: {
      '--color-bg': '#1A0000', '--color-surface': '#2A0A0A', '--color-primary': '#EF5350',
      '--color-primary-hover': '#E57373', '--color-primary-text': '#1A0000', '--color-secondary': '#FFD600',
      '--color-accent': '#FFEE58', '--color-text': '#FFF8E1', '--color-text-muted': '#FFAB91',
      '--color-border': '#3E1A1A', '--color-hot': '#EF5350', '--color-cold': '#42A5F5',
      '--color-success': '#66BB6A', '--color-danger': '#EF5350', '--color-sponsored': '#F48FB1',
    },
  },
  christmas: {
    light: {
      '--color-bg': '#F5FAF5', '--color-surface': '#FFFFFF', '--color-primary': '#B71C1C',
      '--color-primary-hover': '#8E0000', '--color-primary-text': '#FFFFFF', '--color-secondary': '#1B5E20',
      '--color-accent': '#FFD700', '--color-text': '#1B1B1B', '--color-text-muted': '#616161',
      '--color-border': '#C8E6C9', '--color-hot': '#D32F2F', '--color-cold': '#0277BD',
      '--color-success': '#2E7D32', '--color-danger': '#C62828', '--color-sponsored': '#6A1B9A',
    },
    dark: {
      '--color-bg': '#0A1A0A', '--color-surface': '#122412', '--color-primary': '#EF5350',
      '--color-primary-hover': '#E57373', '--color-primary-text': '#0A1A0A', '--color-secondary': '#66BB6A',
      '--color-accent': '#FFD600', '--color-text': '#E8F5E9', '--color-text-muted': '#A5D6A7',
      '--color-border': '#1B3A1B', '--color-hot': '#EF5350', '--color-cold': '#29B6F6',
      '--color-success': '#66BB6A', '--color-danger': '#EF5350', '--color-sponsored': '#CE93D8',
    },
  },
  'mid-autumn': {
    light: {
      '--color-bg': '#FFFDE7', '--color-surface': '#FFFFFF', '--color-primary': '#E65100',
      '--color-primary-hover': '#BF360C', '--color-primary-text': '#FFFFFF', '--color-secondary': '#F9A825',
      '--color-accent': '#FF8F00', '--color-text': '#3E2723', '--color-text-muted': '#8D6E63',
      '--color-border': '#FFF9C4', '--color-hot': '#E65100', '--color-cold': '#0277BD',
      '--color-success': '#558B2F', '--color-danger': '#C62828', '--color-sponsored': '#6A1B9A',
    },
    dark: {
      '--color-bg': '#1A1200', '--color-surface': '#2A1E00', '--color-primary': '#FFB300',
      '--color-primary-hover': '#FFC107', '--color-primary-text': '#1A1200', '--color-secondary': '#FF8F00',
      '--color-accent': '#FFE082', '--color-text': '#FFFDE7', '--color-text-muted': '#FFE082',
      '--color-border': '#3E3200', '--color-hot': '#FF8F00', '--color-cold': '#29B6F6',
      '--color-success': '#9CCC65', '--color-danger': '#FF7043', '--color-sponsored': '#CE93D8',
    },
  },
  'national-day': {
    light: {
      '--color-bg': '#FFF3F0', '--color-surface': '#FFFFFF', '--color-primary': '#D50000',
      '--color-primary-hover': '#B71C1C', '--color-primary-text': '#FFFFFF', '--color-secondary': '#FFD600',
      '--color-accent': '#FFAB00', '--color-text': '#1A1A1A', '--color-text-muted': '#616161',
      '--color-border': '#FFCDD2', '--color-hot': '#D50000', '--color-cold': '#1565C0',
      '--color-success': '#2E7D32', '--color-danger': '#D50000', '--color-sponsored': '#6A1B9A',
    },
    dark: {
      '--color-bg': '#1A0000', '--color-surface': '#300000', '--color-primary': '#FF1744',
      '--color-primary-hover': '#FF5252', '--color-primary-text': '#FFFFFF', '--color-secondary': '#FFD600',
      '--color-accent': '#FFAB00', '--color-text': '#FFEBEE', '--color-text-muted': '#EF9A9A',
      '--color-border': '#4A0000', '--color-hot': '#FF1744', '--color-cold': '#42A5F5',
      '--color-success': '#66BB6A', '--color-danger': '#FF1744', '--color-sponsored': '#CE93D8',
    },
  },
} as const

export type LayoutKey = keyof typeof LAYOUT_PRESETS
export type ScaleKey = keyof typeof SCALE_PRESETS
export type ColorSchemeKey = keyof typeof COLOR_SCHEMES
