export const amazon = {
  
    '--layout-name': 'amazon',
    '--card-border-radius': '0.5rem',
    '--card-shadow': '0 1px 3px rgba(0,0,0,0.08)',
    '--card-shadow-hover': '0 4px 16px rgba(0,0,0,0.12)',
    '--card-border': '1px solid var(--color-border)',
    '--card-bg': 'var(--color-surface)',
    '--card-bg-dark': 'var(--color-surface)',
    '--card-direction': 'column',
    '--card-image-width': '100%',
    '--card-image-height': 'auto',
    '--card-image-ratio': '1/1',
    '--card-padding': '0',
    '--grid-columns-base': '4', // scale adjusts: xs→5, xl→2
    '--nav-style': 'sticky',
    '--nav-blur': 'none',
    '--nav-bg': 'var(--color-nav-bg)',
    '--nav-bg-dark': 'var(--color-nav-bg)',
    '--nav-border': '1px solid var(--color-nav-border)',
    '--sidebar-width': '0px',
    '--sidebar-display': 'none',
    '--border-radius-sm': '0.375rem',
    '--border-radius-md': '0.5rem',
    '--border-radius-lg': '0.625rem',
    '--border-radius-xl': '0.75rem',
    '--content-max-width': '1440px',
    '--glass-bg': 'rgba(255,255,255,0.92)',
    '--glass-bg-dark': 'rgba(30,30,30,0.92)',
    '--glass-blur': 'blur(4px)',
    '--glass-border': '1px solid rgba(255,255,255,0.06)',
    '--glass-border-dark': '1px solid rgba(255,255,255,0.03)',
  } as const;

export default amazon;
