export const minimalist = {
  
    '--layout-name': 'minimalist',
    '--card-border-radius': '0',
    '--card-shadow': 'none',
    '--card-shadow-hover': 'none',
    '--card-border': 'none',
    '--card-bg': 'transparent',
    '--card-bg-dark': 'transparent',
    '--card-direction': 'row',
    '--card-image-width': '64px',
    '--card-image-height': '64px',
    '--card-image-ratio': '1/1',
    '--card-padding': '0.75rem 0',
    '--grid-columns-base': '1', // always 1 col
    '--nav-style': 'static',
    '--nav-blur': 'none',
    '--nav-bg': 'var(--color-nav-bg)',
    '--nav-bg-dark': 'var(--color-nav-bg)',
    '--nav-border': '1px solid var(--color-nav-border)',
    '--sidebar-width': '260px',
    '--sidebar-display': 'block',
    '--border-radius-sm': '2px',
    '--border-radius-md': '4px',
    '--border-radius-lg': '6px',
    '--border-radius-xl': '8px',
    '--content-max-width': '960px',
    '--glass-bg': 'var(--color-surface)',
    '--glass-bg-dark': 'var(--color-surface)',
    '--glass-blur': 'none',
    '--glass-border': '1px solid var(--color-border)',
    '--glass-border-dark': '1px solid var(--color-border)',
  } as const;

export default minimalist;
