export const shopee = {
  
    '--layout-name': 'shopee',
    '--card-border-radius': '0.25rem',
    '--card-shadow': '0 1px 2px rgba(0,0,0,0.05)',
    '--card-shadow-hover': '0 2px 12px rgba(0,0,0,0.12)',
    '--card-border': '1px solid var(--color-border)',
    '--card-bg': 'var(--color-surface)',
    '--card-bg-dark': 'var(--color-surface)',
    '--card-direction': 'column',
    '--card-image-width': '100%',
    '--card-image-height': 'auto',
    '--card-image-ratio': '1/1',
    '--card-padding': '0',
    '--grid-columns-base': '5', // scale adjusts: xs→6, xl→3
    '--nav-style': 'sticky',
    '--nav-blur': 'none',
    '--nav-bg': 'var(--color-nav-bg)',
    '--nav-bg-dark': 'var(--color-nav-bg)',
    '--nav-border': '1px solid var(--color-nav-border)',
    '--sidebar-width': '220px',
    '--sidebar-display': 'block',
    '--border-radius-sm': '0.125rem',
    '--border-radius-md': '0.25rem',
    '--border-radius-lg': '0.375rem',
    '--border-radius-xl': '0.5rem',
    '--content-max-width': '1400px',
    '--glass-bg': 'rgba(255,255,255,0.9)',
    '--glass-bg-dark': 'rgba(30,30,30,0.9)',
    '--glass-blur': 'blur(6px)',
    '--glass-border': '1px solid rgba(255,255,255,0.08)',
    '--glass-border-dark': '1px solid rgba(255,255,255,0.04)',
  } as const;

export default shopee;
